### ISSUE TITLE
Suggestion: Be able to sort goals into card categories that they are available in

### ISSUE THREAD

**Issue by Pikastroff** [cjs8487/PlayBingo#11]
The most obvious example would be to use that to sort goals into "Short" and "Long" variants ala Bingosync, but beyond that, with easy customization of which goals go to which board categories, there's a lot you could do. This would be INDEPENDANT of the difficulty tiers that are already included for the SRLv5 generation of the boards (although people can perfectly use that to determine which goals go to which card, but that's up to the card creators).

**Comment by cjs8487** [comment]
Difficulty variants should largely cover this, and this will be fully covered by the true variant system in the future. Closing because the core suggestion is addressed.
